"""add create_at to book

Revision ID: 7232b9f0d8d2
Revises: 
Create Date: 2024-10-25 10:33:45.899888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7232b9f0d8d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
