"""update

Revision ID: 983e1a5b11f3
Revises: a27d4ddc6e34
Create Date: 2024-11-02 18:04:17.838413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983e1a5b11f3'
down_revision = 'a27d4ddc6e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('publisher')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
