"""update book

Revision ID: bd7afd7f5486
Revises: 983e1a5b11f3
Create Date: 2024-11-10 14:43:21.628926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7afd7f5486'
down_revision = '983e1a5b11f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('video')
        batch_op.drop_column('pdf')

    # ### end Alembic commands ###
