"""update

Revision ID: f2f0a1fcb647
Revises: 882f654cc1b6
Create Date: 2024-11-02 15:45:16.793200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f0a1fcb647'
down_revision = '882f654cc1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
